use anyhow::{Context, Result};
use log::{info, warn};
use std::fs;
use std::path::Path;
use std::process::Command;

use crate::dev::ensure_cargo_bin_config;
use crate::generate;

pub fn handle_build(bin: bool, out_dir: &str) -> Result<()> {
    let project_dir = std::env::current_dir()?;
    info!("Generating routes...");

    generate::generate_all(&project_dir, 3000)?;

    if bin {
        build_binary(&project_dir, out_dir)?;
    } else {
        build_static_site(&project_dir, out_dir)?;
    }

    Ok(())
}

fn build_binary(project_dir: &Path, out_dir: &str) -> Result<()> {
    info!("Building embedded binary to {}...", out_dir);
    ensure_cargo_bin_config(project_dir)?;

    let status = Command::new("cargo")
        .args(["build", "--release", "--bin", "lithe-app"])
        .current_dir(project_dir)
        .status()
        .context("Failed to build binary")?;

    if status.success() {
        fs::create_dir_all(out_dir)?;
        let target_binary = project_dir.join("target/release/lithe-app");
        let dest_binary = Path::new(out_dir).join("lithe-app");
        if target_binary.exists() {
            fs::copy(&target_binary, &dest_binary)?;
            info!("Binary written to {}", dest_binary.display());
        }
    }

    Ok(())
}

fn build_static_site(project_dir: &Path, out_dir: &str) -> Result<()> {
    info!("Building static site to {}...", out_dir);

    let lithe_dir = project_dir.join(".lithe");

    let builder_content = generate_static_builder_content(out_dir);
    fs::write(lithe_dir.join("static_builder.rs"), &builder_content)?;

    let cargo_path = project_dir.join("Cargo.toml");
    let content = fs::read_to_string(&cargo_path)?;

    let builder_bin = r#"

[[bin]]
name = "lithe-static-builder"
path = ".lithe/static_builder.rs"
"#;

    if !content.contains("lithe-static-builder") {
        fs::write(&cargo_path, format!("{}{}", content, builder_bin))?;
    }

    let status = Command::new("cargo")
        .args(["run", "--bin", "lithe-static-builder"])
        .current_dir(project_dir)
        .status()
        .context("Failed to run static builder")?;

    if status.success() {
        info!("Static site built successfully to {}", out_dir);
    } else {
        warn!("Static build failed");
    }

    Ok(())
}

fn generate_static_builder_content(out_dir: &str) -> String {
    format!(
        r#"// Auto-generated by lithe-cli - do not edit manually
#[path = "routes.rs"]
mod routes;

fn main() {{
    let out_dir = "{out_dir}";
    let _ = std::fs::remove_dir_all(out_dir);

    let routes = routes::routes();
    for route in routes {{
        let content = routes::dispatch(route);
        let path = if route == "/" {{
            format!("{{}}/index.html", out_dir)
        }} else {{
            format!("{{}}{{}}/index.html", out_dir, route)
        }};
        let dir = std::path::Path::new(&path).parent().unwrap();
        std::fs::create_dir_all(dir).unwrap();
        std::fs::write(&path, content).unwrap();
        println!("Wrote {{}}", path);
    }}
}}
"#,
        out_dir = out_dir
    )
}
