use anyhow::{Context, Result};
use regex::Regex;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone)]
pub struct ClientFunction {
    pub full_path: String,
}

pub fn discover_client_functions(project_dir: &Path) -> Result<Vec<ClientFunction>> {
    let src_dir = project_dir.join("src");
    let mut functions = Vec::new();
    if !src_dir.exists() {
        return Ok(functions);
    }
    scan_directory(&src_dir, &src_dir, &mut functions)?;
    Ok(functions)
}

fn scan_directory(dir: &Path, src_root: &Path, functions: &mut Vec<ClientFunction>) -> Result<()> {
    for entry in fs::read_dir(dir).context(format!("Failed to read directory: {:?}", dir))? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            scan_directory(&path, src_root, functions)?;
        } else if path.extension().map_or(false, |ext| ext == "rs") {
            scan_file(&path, src_root, functions)?;
        }
    }
    Ok(())
}

fn scan_file(file_path: &Path, src_root: &Path, functions: &mut Vec<ClientFunction>) -> Result<()> {
    let content =
        fs::read_to_string(file_path).context(format!("Failed to read file: {:?}", file_path))?;
    // Match #[client] or #[lithe::client] followed by pub fn
    let re = Regex::new(r#"#\[(?:[\w:]+::)?client\]\s*pub(?:\([^)]+\))?\s+fn\s+(\w+)"#)
        .context("Failed to compile regex")?;
    let relative = file_path
        .strip_prefix(src_root)
        .context("File not under src root")?;
    let module_path = relative
        .with_extension("")
        .to_string_lossy()
        .replace(['/', '\\'], "::");
    for cap in re.captures_iter(&content) {
        let fn_name = cap[1].to_string();
        let full_path = format!("{}::{}", module_path, fn_name);
        functions.push(ClientFunction { full_path });
    }
    Ok(())
}

pub fn generate_wasm_exports(project_dir: &Path, functions: &[ClientFunction]) -> Result<()> {
    let lithe_dir = project_dir.join(".lithe");
    fs::create_dir_all(&lithe_dir).context("Failed to create .lithe directory")?;
    let mut output = String::new();
    output.push_str("// Auto-generated by lithe-cli - do not edit manually\n");
    output.push_str("use wasm_bindgen::prelude::*;\n\n");
    for (i, func) in functions.iter().enumerate() {
        let js_name = func.full_path.replace("::", "_");
        output.push_str(&format!(
            r#"#[wasm_bindgen(js_name = "{}")]
pub fn __wasm_export_{}() {{
    crate::{}();
}}
"#,
            js_name, i, func.full_path
        ));
    }
    fs::write(lithe_dir.join("wasm_exports.rs"), output)
        .context("Failed to write .lithe/wasm_exports.rs")?;
    Ok(())
}
