// Auto-generated by lithe-cli - do not edit manually

#[path = "../src/utils.rs"]
pub mod utils;

#[path = "../src/pages/index.rs"]
pub mod index_page;

#[path = "../src/pages/about.rs"]
pub mod about_page;

#[path = "../src/pages/contact.rs"]
pub mod contact_page;

pub mod pages {
    pub use super::index_page as index;
    pub use super::about_page as about;
    pub use super::contact_page as contact;
}

#[cfg(target_arch = "wasm32")]
#[path = "wasm_exports.rs"]
mod wasm_exports;
