// Auto-generated by lithe-cli - do not edit manually
use axum::{Router, extract::Path, response::{Html, IntoResponse, Response}, routing::{get, post}, body::Body, http::{header, StatusCode}};
use rust_embed::RustEmbed;
#[path = "routes.rs"]
mod routes;
#[path = "rpc.rs"]
mod rpc;

#[derive(RustEmbed)]
#[folder = ".lithe/public/"]
struct Assets;

async fn handle_root() -> Html<String> {
    Html(routes::dispatch("/"))
}

async fn handle_path(Path(path): Path<String>) -> Html<String> {
    Html(routes::dispatch(&format!("/{}", path)))
}

async fn static_handler(Path(path): Path<String>) -> impl IntoResponse {
    let path = path.trim_start_matches('/');
    if let Some(content) = Assets::get(path) {
        let mime = mime_guess::from_path(path).first_or_octet_stream();
        Response::builder()
            .header(header::CONTENT_TYPE, mime.as_ref())
            .body(Body::from(content.data))
            .unwrap()
    } else {
        Response::builder()
            .status(StatusCode::NOT_FOUND)
            .body(Body::from("404 Not Found"))
            .unwrap()
    }
}

#[tokio::main]
async fn main() {
    let app = Router::new()
        .route("/api/lithe-rpc", post(rpc::handle_rpc))
        .route("/public/*path", get(static_handler))
        .route("/", get(handle_root))
        .route("/*path", get(handle_path));
    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    println!("Listening on http://localhost:3000");
    axum::serve(listener, app).await.unwrap();
}
