// Auto-generated by lithe-cli - do not edit manually
use lithe::render_page;

#[path = "../src/pages/index.rs"]
mod index_page;
#[path = "../src/pages/about.rs"]
mod about_page;
#[path = "../src/pages/contact.rs"]
mod contact_page;

pub fn dispatch(path: &str) -> String {
    match path {
        "/" => render_page(index_page::page(), "rust2"),
        "/about" => render_page(about_page::page(), "rust2"),
        "/contact" => render_page(contact_page::page(), "rust2"),
        _ => "404 Not Found".to_string(),
    }
}

pub fn routes() -> Vec<&'static str> {
    vec!["/", "/about", "/contact"]
}
