// Auto-generated by build.rs - do not edit manually
use lithe::render_to_string;

#[path = "../src/pages/index.rs"]
mod index_page;
#[path = "../src/pages/about.rs"]
mod about_page;
#[path = "../src/pages/contact.rs"]
mod contact_page;

pub fn dispatch(path: &str) -> String {
    match path {
        "/" => render_to_string(&index_page::page()),
        "/about" => render_to_string(&about_page::page()),
        "/contact" => render_to_string(&contact_page::page()),
        _ => "404 Not Found".to_string(),
    }
}

pub fn routes() -> Vec<&'static str> {
    vec!["/", "/about", "/contact"]
}
