// Auto-generated by lithe-cli - do not edit manually
use axum::{Json, response::IntoResponse, http::StatusCode};
use lithe::rpc::{RpcRequest, RpcResponse};

pub async fn handle_rpc(Json(req): Json<RpcRequest>) -> impl IntoResponse {
    let result = match req.function.as_str() {
        "get_server_data" | "utils_get_server_data" => {
            let args: i32 = serde_json::from_value(req.args).unwrap();
            rust::utils::__lithe_rpc_get_server_data(args).await
        }
        _ => return (StatusCode::NOT_FOUND, "Function not found").into_response(),
    };

    Json(RpcResponse { result }).into_response()
}
