// Auto-generated by lithe-cli - do not edit manually
#[path = "routes.rs"]
mod routes;

fn main() {
    let out_dir = "dist";
    let _ = std::fs::remove_dir_all(out_dir);

    let routes = routes::routes();
    for route in routes {
        let content = routes::dispatch(route);
        let path = if route == "/" {
            format!("{}/index.html", out_dir)
        } else {
            format!("{}{}/index.html", out_dir, route)
        };
        let dir = std::path::Path::new(&path).parent().unwrap();
        std::fs::create_dir_all(dir).unwrap();
        std::fs::write(&path, content).unwrap();
        println!("Wrote {}", path);
    }
}
