// Auto-generated by lithe-cli - do not edit manually
#[path = "routes.rs"]
mod routes;
fn main() {
    let out_dir = "dist";
    let _ = std::fs::remove_dir_all(out_dir);

    let public_dir = std::path::Path::new("src/public");
    if public_dir.exists() {
        let dest = std::path::Path::new(out_dir).join("public");
        copy_dir_all(public_dir, dest).unwrap();
        println!("Copied src/public to {}/public", out_dir);
    }
    let routes = routes::routes();
    for route in routes {
        let content = routes::dispatch(route);
        let path = if route == "/" {
            format!("{}/index.html", out_dir)
        } else {
            format!("{}{}/index.html", out_dir, route)
        };
        let dir = std::path::Path::new(&path).parent().unwrap();
        std::fs::create_dir_all(dir).unwrap();
        std::fs::write(&path, content).unwrap();
        println!("Wrote {}", path);
    }
}
fn copy_dir_all(src: impl AsRef<std::path::Path>, dst: impl AsRef<std::path::Path>) -> std::io::Result<()> {
    std::fs::create_dir_all(&dst)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        if ty.is_dir() {
            copy_dir_all(entry.path(), dst.as_ref().join(entry.file_name()))?;
        } else {
            std::fs::copy(entry.path(), dst.as_ref().join(entry.file_name()))?;
        }
    }
    Ok(())
}
