// Auto-generated by lithe-cli - do not edit manually
use wasm_bindgen::prelude::*;

#[wasm_bindgen(js_name = "pages_index_handle_click")]
pub fn __wasm_export_0() {
    crate::pages::index::handle_click();
}
