// Auto-generated by lithe-cli - do not edit manually
use wasm_bindgen::prelude::*;

#[wasm_bindgen(js_name = "pages_index_handle_local_click")]
pub fn __wasm_export_0() {
    crate::pages::index::handle_local_click();
}
#[wasm_bindgen(js_name = "utils_alert_from_utils")]
pub fn __wasm_export_1() {
    crate::utils::alert_from_utils();
}
