use std::fs;
use std::path::Path;

fn main() {
    println!("cargo::rerun-if-changed=src/pages/");

    let pages_dir = Path::new("src/pages");
    let output_path = Path::new(".lithe/routes.rs");

    fs::create_dir_all(".lithe").expect("Failed to create .lithe directory");

    let mut pages: Vec<(String, String, String)> = Vec::new();

    if pages_dir.exists() {
        for entry in fs::read_dir(pages_dir).expect("Failed to read src/pages directory") {
            let entry = entry.expect("Failed to read directory entry");
            let path = entry.path();

            if path.extension().map_or(false, |ext| ext == "rs") {
                let file_stem = path.file_stem().unwrap().to_str().unwrap().to_string();

                let route = if file_stem == "index" {
                    "/".to_string()
                } else {
                    format!("/{}", file_stem.replace('_', "-"))
                };

                let module_name = format!("{}_page", file_stem.replace('-', "_"));

                let relative_path = format!("../src/pages/{}.rs", file_stem);

                pages.push((route, module_name, relative_path));
            }
        }
    }

    pages.sort_by(|a, b| {
        if a.0 == "/" {
            std::cmp::Ordering::Less
        } else if b.0 == "/" {
            std::cmp::Ordering::Greater
        } else {
            a.0.cmp(&b.0)
        }
    });

    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs - do not edit manually\n");
    output.push_str("use lithe::render_to_string;\n\n");

    for (_, module_name, relative_path) in &pages {
        output.push_str(&format!("#[path = \"{}\"]\n", relative_path));
        output.push_str(&format!("mod {};\n", module_name));
    }

    output.push_str("\npub fn dispatch(path: &str) -> String {\n");
    output.push_str("    match path {\n");
    for (route, module_name, _) in &pages {
        output.push_str(&format!(
            "        \"{}\" => render_to_string(&{}::page()),\n",
            route, module_name
        ));
    }
    output.push_str("        _ => \"404 Not Found\".to_string(),\n");
    output.push_str("    }\n");
    output.push_str("}\n");

    output.push_str("\npub fn routes() -> Vec<&'static str> {\n");
    output.push_str("    vec![");
    let routes: Vec<String> = pages
        .iter()
        .map(|(route, _, _)| format!("\"{}\"", route))
        .collect();
    output.push_str(&routes.join(", "));
    output.push_str("]\n");
    output.push_str("}\n");

    fs::write(output_path, output).expect("Failed to write .lithe/routes.rs");
}
